POST http://localhost:3000/1/register
Content-Type: application/json

{
    "teach_type": "tecnico",
    "high_scholl": 3,
    "name": "testeUser",
    "email": "user@email.com",
    "password": "user123",
    "cpf": "00011100100",
    "scholl": "Etec Antonio Devisate",
    "phone_number": 14999939999
}

###
POST http://localhost:3000/login 

{
    "email": "isaac@email.com",
    "password": "admin123"
}

### 
POST http://localhost:3000/material-class
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlzYWFjQGVtYWlsLmNvbSIsImV4cCI6MTcyNTY3ODYzMSwiaWQiOjIsIm5hbWUiOiJpc2FhYyIsInVzZXJfdHlwZSI6Im1lbnRvciJ9.GieyslJTBMj10dei8s24DFIT-IcadXx9BuOkBYefcV0

{
    "title": "Aula 1",
    "subject": "principios básicos de html e css",
    "content": "### HTML (Linguagem de Marcação de HiperTexto)\n- é o bloco de construção mais básico da web. Define o significado e a estrutura do conteúdo da web. Outras tecnologias além do HTML geralmente são usadas para descrever a aparência/apresentação (CSS) ou a funcionalidade/comportamento (JavaScript) de uma página da web.\n### Cascading Style Sheets (CSS)\n- é usado para formatar o layout de uma página da web. Com CSS, você pode controlar a cor, a fonte, o tamanho do texto, o espaçamento entre os elementos, como os elementos são posicionados e dispostos, quais imagens ou cores de fundo serão usadas, diferentes exibições para diferentes dispositivos e tamanhos de tela e muito mais!"
}

### 
POST http://localhost:3000/project 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlzYWFjQGVtYWlsLmNvbSIsImV4cCI6MTcyNTU4MjcyMiwiaWQiOjIsIm5hbWUiOiJpc2FhYyIsInVzZXJfdHlwZSI6Im1lbnRvciJ9.Jtt2fBSdnWH7Gw8Ri4_XrfXnBEWb1cLQF7frS-hYg_s

{
    "title": "ProjectTeste",
    "description": "Isso é um incrivel projeto de teste, de um user teste",
    "video_url": "https://youtu.be/nJkVHusJp6E?si=KPmVLomxSvrE3FIt",
    "project_url": "https://github.com"
}

###
POST http://localhost:3000/evaluate/project

{
    "project_id": 1,
    "quality_grade": 10, 
    "creativity_grade": 10
}

###
GET http://localhost:3000/project/tecnico
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlzYWFjQGVtYWlsLmNvbSIsImV4cCI6MTcyNTU4MjcyMiwiaWQiOjIsIm5hbWUiOiJpc2FhYyIsInVzZXJfdHlwZSI6Im1lbnRvciJ9.Jtt2fBSdnWH7Gw8Ri4_XrfXnBEWb1cLQF7frS-hYg_s
###
GET http://localhost:3000/project
Authorization: Bearer TOKEN

### 
GET http://localhost:3000/material-class

### 
GET http://localhost:3000/material-class/1

### 
GET http://localhost:3000/rank/tecnico

###
GET http://localhost:3000/bootcamp