POST http://localhost:3000/1/register
Content-Type: application/json

{
    "teach_type": "tecnico",
    "high_scholl": 3,
    "name": "testeUser",
    "email": "user@email.com",
    "password": "user123",
    "cpf": "00011100100",
    "scholl": "Etec Antonio Devisate",
    "phone_number": 14999939999
}

###
POST http://localhost:3000/login 

{
    "email": "joze@email.com",
    "password": "arnaldo123"
}

### 
POST http://localhost:3000/material-class
Authorization: Bearer TOKEN

{
    "title": "Aula 1",
    "subject": "principios básicos de html e css",
    "content": "### HTML (Linguagem de Marcação de HiperTexto)\n- é o bloco de construção mais básico da web. Define o significado e a estrutura do conteúdo da web. Outras tecnologias além do HTML geralmente são usadas para descrever a aparência/apresentação (CSS) ou a funcionalidade/comportamento (JavaScript) de uma página da web.\n### Cascading Style Sheets (CSS)\n- é usado para formatar o layout de uma página da web. Com CSS, você pode controlar a cor, a fonte, o tamanho do texto, o espaçamento entre os elementos, como os elementos são posicionados e dispostos, quais imagens ou cores de fundo serão usadas, diferentes exibições para diferentes dispositivos e tamanhos de tela e muito mais!"
}

### 
POST http://localhost:3000/project 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwiZXhwIjoxNzI1NDc0MjQ0LCJpZCI6OSwibmFtZSI6InRlc3RlVXNlciIsInVzZXJfdHlwZSI6ImVzdHVkYW50ZSJ9.RamIOpuLc3zJNJnXTcZow70OBHmH5jDZWrwA5O35-Eg

{
    "title": "ProjectTeste",
    "description": "Isso é um incrivel projeto de teste, de um user teste",
    "video_url": "https://youtu.be/nJkVHusJp6E?si=KPmVLomxSvrE3FIt",
    "project_url": "https://github.com"
}

###
POST http://localhost:3000/evaluate/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvemVAZW1haWwuY29tIiwiZXhwIjoxNzI1NDc5OTE3LCJpZCI6MSwibmFtZSI6ImpvemUiLCJ1c2VyX3R5cGUiOiJtZW50b3IifQ.1KgVlbAfuuEW8234Sq0088CtnGSh553D-dns5GBkiWs

{
    "project_id": 2,
    "quality_grade": 10, 
    "creativity_grade": 10
}

###
GET http://localhost:3000/project/tecnico

###
GET http://localhost:3000/project
Authorization: Bearer TOKEN

### 
GET http://localhost:3000/material-class

### 
GET http://localhost:3000/material-class/1

### 
GET http://localhost:3000/rank/tecnico

###
GET http://localhost:3000/bootcamp